using System.Text.RegularExpressions;

string[] roots =
[
    @"D:\Projects\SpatialDb\SpatialDbLib",
    @"D:\Projects\SpatialDb\SpatialDbApp",
    @"D:\Projects\SpatialDb\SpatialDbLibTest",
    @"D:\Projects\SpatialDb\SpatialGame",
    @"D:\Projects\SpatialDb\SpatialGameTest",
    @"D:\Projects\SpatialDb\SparseLattice",
    @"D:\Projects\SpatialDb\SparseLattice.Test",
    @"D:\Projects\SpatialDb\SparseLattice.Perf",
];

// Looks like a C# code line: must contain at least one of these patterns
static bool IsCodeLine(string l)
{
    // Must have at least one C#-ish token
    if (l.Contains(';') || l.Contains("=>") || l.Contains("public ") ||
        l.Contains("private ") || l.Contains("protected ") || l.Contains("internal ") ||
        l.Contains("static ") || l.Contains("override ") || l.Contains("return ") ||
        l.Contains("var ") || l.Contains("new ") || l.Contains("if (") ||
        l.Contains("for (") || l.Contains("foreach (") || l.Contains("while (") ||
        l.Contains(".Add(") || l.Contains(".Select(") || l.Contains(".Where(") ||
        l.Contains("async ") || l.Contains("await ") || l.Contains("Task<") ||
        l.Contains("string ") || l.Contains("int ") || l.Contains("float ") ||
        l.Contains("double ") || l.Contains("bool ") || l.Contains("void "))
        return true;
    return false;
}

var lines = new List<string>(1200);
var seen  = new HashSet<string>(StringComparer.Ordinal);

foreach (string root in roots)
{
    if (!Directory.Exists(root)) { Console.WriteLine($"  skip (missing): {root}"); continue; }

    foreach (string file in Directory.GetFiles(root, "*.cs", SearchOption.AllDirectories))
    {
        if (lines.Count >= 1000) break;

        string fp = file.Replace('\\', '/').ToLowerInvariant();
        if (fp.Contains("/bin/") || fp.Contains("/obj/") || fp.Contains("/testdata/")) continue;
        if (fp.Contains("extensionguide") || fp.Contains("_guide") || fp.Contains("guide.cs")) continue;

        foreach (string raw in File.ReadLines(file))
        {
            if (lines.Count >= 1000) break;

            string l = raw.Trim();
            if (l.Length < 10 || l.Length > 200) continue;
            if (l.StartsWith("//") || l.StartsWith("/*") || l.StartsWith("*") || l.StartsWith("///")) continue;
            if (l.StartsWith("using ") || l.StartsWith("namespace ") || l.StartsWith("#")) continue;
            if (l.StartsWith("[") && l.EndsWith("]")) continue;          // bare attributes
            if (Regex.IsMatch(l, @"^[{}\[\]();,\s]+$")) continue;        // punctuation-only
            if (l.Contains("<auto-generated>")) continue;
            if (!IsCodeLine(l)) continue;                                 // must look like C#
            if (!seen.Add(l)) continue;                                   // deduplicate

            lines.Add(l);
        }
    }
    if (lines.Count >= 1000) break;
}

string outDir  = @"D:\Projects\SpatialDb\SparseLattice.Perf\TestData\Samples";
string outFile = Path.Combine(outDir, "samples.txt");
Directory.CreateDirectory(outDir);

int take = Math.Min(lines.Count, 1000);
File.WriteAllLines(outFile, lines.Take(take), System.Text.Encoding.UTF8);

Console.WriteLine($"Wrote {take} lines to {outFile}");
Console.WriteLine($"\nFirst 5:");
foreach (string l in lines.Take(5)) Console.WriteLine($"  {l}");
Console.WriteLine($"\nLast 5:");
foreach (string l in lines.Skip(take - 5).Take(5)) Console.WriteLine($"  {l}");
Console.WriteLine($"\nDone.");
